# Generated by Django 4.1 on 2024-02-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student_Data",
            fields=[
                ("student_name", models.CharField(max_length=255)),
                (
                    "register_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("student_email", models.EmailField(max_length=254)),
                ("borrowed_books_count", models.IntegerField(default=0)),
                (
                    "borrowal_fine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Borrowed_Book",
            fields=[
                (
                    "book_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("book_name", models.CharField(max_length=255)),
                ("borrowed_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "fine_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "borrower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_api.student_data",
                    ),
                ),
            ],
        ),
    ]
