# Generated by Django 4.1 on 2024-02-16 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BorrowedBook",
            new_name="Borrowed_Book",
        ),
        migrations.RenameModel(
            old_name="StudentData",
            new_name="Student_Data",
        ),
    ]
