# Generated by Django 4.1 on 2024-02-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="borrowed_books",
                to="library_api.studentdata",
            ),
        ),
    ]
