# Generated by Django 4.1 on 2024-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0002_alter_borrowedbook_borrower"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowedbook",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
