# Generated by Django 4.1 on 2024-02-16 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library_api", "0003_alter_borrowedbook_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowedbook",
            name="id",
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="book_id",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="borrowedbook",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="library_api.studentdata",
            ),
        ),
    ]
